In [8]:
import numpy as np
import random as random

#0/1 Knapsack problem
#We have one of each item of various weight. Given a max weight of knapsack how can we maximise the ulitity value

#Useful links
#https://www.youtube.com/watch?v=8LusJS5-AGo
#http://www.geeksforgeeks.org/dynamic-programming-set-10-0-1-knapsack-problem/


#W is the weight capacity of the knapsack
#wt is a list of our item's weights/masses
#val is our list of item values

#def knapsack(W, wt, val):
    #Create our table of results
#    n = len(val)
#   K =[[0 for x in range(W+1)] 0 for x in range(n+1)]
    
    #Now begin populating our table
#    for i in range(n+1):
#        for w in range(W+1):
#             for i in range(n+1):
#                if i==0 or w==0:
#                    K[i][w] = 0
#                elif wt[i-1] <= w:
#                    K[i][w] = max(val[i-1] + K[i-1][w-wt[i-1]],  K[i-1][w])
#                else:
#                    K[i][w] = K[i-1][w]
#   return K[n][W]

#Make this now work around max values as we have a zero array    
def arrayPath(frameCount, extraDiag):
    errors = np.zeros((7,7))
    for i in range(0,5):
        errors[i,i+1]=random.randint(2,40)
        if(i+2>7):
            continue
        errors[i,i+2]=random.randint(2,40)
    print "This is our error array"
    print errors
    #Array is populated now assess costs
    costmatrix = np.zeros((7, 7))
    #First Pass of Populate 
    for i in range(0,frameCount):
        for j in range(i+1, i+extraDiag+2):
            minvalue = 0
            minindex = 0
            #THIS MIN FINDING NEEDS WORK
            for k in range(1, extraDiag+2):
                if(errors[i-k, i]< minvalue):
                    minvalue = errors[i-k, i]
                    #Double check that this next line is indeed the correct index
                    minindex = i-k
            #Why is this term a += and not just an =?
            errors[i, j]+= minvalue
            #There is an OFF BY ONE error here
            costmatrix [i, j] = minindex
            #Need a way to rezero the max index and max value
    print "This is the re-evaluted error array"
    print errors
    print "This is our resulting cost matrix"
    print costmatrix
    #Second Pass Trace Back Min Cost
    #Multi-dimensional argmin to set initial values of s and d
    s = 5
    d = 4
    p = []
    while(s>frameCount):
        #Prepend to List and work our way back up through the cost matrix
        p.insert(0, s)
        b = costmatrix[s, d]
        d = s
        s = b
    print "These are our desired frames"
    print p
    return p

arrayPath(5, 0)


This is our error array
[[  0.   3.  25.   0.   0.   0.   0.]
 [  0.   0.  32.  37.   0.   0.   0.]
 [  0.   0.   0.  13.  29.   0.   0.]
 [  0.   0.   0.   0.   7.  15.   0.]
 [  0.   0.   0.   0.   0.  15.  20.]
 [  0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.]]
This is the re-evaluted error array
[[  0.   3.  25.   0.   0.   0.   0.]
 [  0.   0.  32.  37.   0.   0.   0.]
 [  0.   0.   0.  13.  29.   0.   0.]
 [  0.   0.   0.   0.   7.  15.   0.]
 [  0.   0.   0.   0.   0.  15.  20.]
 [  0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.]]
This is our resulting cost matrix
[[ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]]
These are our desired frames
[]


[]